on: 
  pull_request: 
  push: 
    branches:
      - master

jobs:
  testing:
    runs-on: ubuntu-latest
    name: Execute test suites for torrent.go
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Testing step
        uses: ./.github/actions/testing/
